### ISSUE TITLE
undefined method `reverse' for nil:NilClass

### ISSUE THREAD

**Issue by lmany** [owen2345/camaleon-cms#979] opened 2020-11-19 02:00 UTC
![image](https://user-images.githubusercontent.com/2327160/99610986-1d583f80-2a13-11eb-8a70-3412a442a47d.png)

I'm using camaleon_cms 2.5.0
ruby 2.6.4

rails (5.2.4.4, 5.2.4.2)

**Comment by brian-kephart** [comment] 2020-11-19 22:43
This is a duplicate of #936, fixed in #937. Updating Camaleon will fix it.

**Closed** 2020-11-19 23:43 UTC
