### ISSUE TITLE
Unable to insert/edit image

### ISSUE THREAD

**Issue by splybon** [owen2345/camaleon-cms#175] opened 2015-10-19 18:19 UTC
![screen shot 2015-10-19 at 2 19 36 pm](https://cloud.githubusercontent.com/assets/6655513/10586813/359d41b8-766c-11e5-9dce-97a0a1a3ddcf.png)

When I click the browse icon, the media box will pop up behind it, but I'm unable to select it without closing the insert/edit image box in front of it.  However, if you close the insert/edit image box in front of it, the picture can't be inserted.

Is this a bug other people are experiencing as well? Any work around for this?

**Comment by cmckni3** [comment] 2015-10-19 20:19
Should be fixed. Duplicate of #147

What version of camaleon are you running?

**Comment by splybon** [comment] 2015-10-20 12:24
I'm using 1.0.3 - I believe that is the latest one.

**Closed** 2015-10-20 13:02 UTC

**Comment by cmckni3** [comment] 2015-10-20 14:49
:+1: No problem
